### ISSUE TITLE
emptyEditEnd 为NO时，删除的问题

### ISSUE THREAD

**Issue by chlxb** [MengLiMing/CodeView#2]
你好，当有下划线的时候，emptyEditEnd 设置为NO, 当输入的内容超过可输入位数的时候，删除无法删除第一个字符 ，因为通知里只判断了  length > _textArray.count ， 此时 _textArray 再添加一个 object 有可能大于 _lineNum

**Comment by MengLiMing** [comment]
谢谢你的提醒，已经修复了
